package com.qe.vt.zprime.constants;

public class Locators {

	public static final String ZPRIME_MAINLOGO_XPATH = "(//img[@src='/assets/zprime_logo-0iecBR0-.png'])[1]";
	public static final String LEFT_MENUBAR_XPATH = "(//button[@type='button'])[1]";
	public static final String LEFT_MENUBAR_BACKARROW_XPATH = "//span[@aria-label='left']";
	public static final String ZPRIME_LOGO_XPATH = "(//img[@src='/assets/zprime_logo-0iecBR0-.png'])[2]";
	public static final String SELECT_PAGE_TEXT_XPATH = "//h3[text()='Select your page']";
	public static final String LEFT_MENUBAR_COMPLIANCE_XPATH = "(//span[text()='Compliance'])[2]";
	public static final String COMPLIANCE_DATERANGE_PICKER_XPATH = "//div[@class='ant-picker ant-picker-range ant-picker-filled css-j9bb5n']";
	public static final String DATE_PREVIOUS_BUTTON_XPATH = "(//button[@tabindex='-1'])[2]";
	public static final String COMPLIANCE_STARTDATE_XPATH = "//input[@placeholder='Start date']";
	public static final String COMPLIANCE_ENDDATE_XPATH = "//input[@placeholder='End date']";
	public static final String COMPLIANCE_SEARCH_BAR_XPATH = "//input[@placeholder='Search']";
	public static final String COMPLIANCE_USER_DROPDOWN_XPATH = "//span[text()='User 01']";
	public static final String COMPLIANCE_USER_PROFILE_XPATH = "//a[@href='/profile']";
	public static final String COMPLIANCE_USER_SETTINGS_XPATH = "(//li[@class='ant-dropdown-menu-item ant-dropdown-menu-item-only-child'])[2]";
	public static final String COMPLIANCE_USER_LOGOUT_XPATH = "//span[text()='Logout']";
	public static final String ZPRIME_LOGO_IMAGE_XPATH = "//img[@src='/assets/zprime_logo-0iecBR0-.png']";
	public static final String LEFT_ENTRYPOINT_PERFORMANCE_XPATH = "//div[text()='Performance']";
	public static final String LEFT_MENUBAR_PERFORMANCE_XPATH = "//span[text()='Performance']";
	public static final String PERFORMANCE_DROP_LIST_CSS = "svg[data-icon='caret-down']";
	public static final String PERFORMANCE_DROPLIST_REACTOR1_XPATH = "//span[text()='Reactor 1']";
	public static final String PERFORMANCE_DROPLIST_REACTOR2_XPATH = "//span[text()='Reactor 2']";
	public static final String PERFORMANCE_OVERALL_SUMMARY_XPATH = "//div[text()='Overall/Summary']";
	public static final String REACTOR1_BUTTON_XPATH = "//div[text()='Reactor 1']";
	public static final String REACTOR2_BUTTON_XPATH = "//div[text()='Reactor 2']";
	public static final String PRODUCTIVITY_XPATH = "(//span[text()='Productivity'])[1]";
	public static final String PRODUCTIVITY_DATERANGE_PICKER_XPATH = "//div[@class='ant-picker ant-picker-range ant-picker-filled css-j9bb5n']";
	public static final String PRODUCTIVITY_STARTDATE_XPATH = "//input[@placeholder='Start date']";
	public static final String PRODUCTIVITY_ENDDATE_XPATH = "//input[@placeholder='End date']";
	public static final String PRODUCTIVITY_SEARCH_BAR_XPATH = "//input[@class='ant-input css-j9bb5n']";
	public static final String OPERATIONAL_INSIGHTS_XPATH = "//span[text()='Operational Insights']";
	public static final String OPERATIONAL_INSIGHTS_DATERANGE_PICKER_XPATH = "//div[@class='ant-picker ant-picker-range ant-picker-filled css-j9bb5n']";
	public static final String OPERATIONAL_INSIGHTS_SATRTDATE_XPATH = "//input[@placeholder='Start date']";
	public static final String OPERATIONAL_INSIGHTS_ENDDATE_XPATH = "//input[@placeholder='End date']";
	public static final String OPERATIONAL_INSIGHTS_SEARCHBAR_XPATH = "//input[@class='ant-input css-j9bb5n']";
	public static final String FLOW_METER_VS_FEEDING_PUMP_X_AXIS_DROPDOWN_XPATH = "(//span[@class='ant-select-selection-item'])[1]";
	public static final String FLOW_METER_VS_FEEDING_PUMP_X_AXIS_OPTION1_XPATH = "(//div[@class='ant-select-item-option-content'])[1]";
	public static final String FLOW_METER_VS_FEEDING_PUMP_X_AXIS_OPTION2_XPATH = "(//div[@class='ant-select-item-option-content'])[2]";
	public static final String FLOW_METER_VS_FEEDING_PUMP_X_AXIS_OPTION3_XPATH = "(//div[@class='ant-select-item-option-content'])[3]";
	public static final String FLOW_METER_VS_FEEDING_PUMP_Y_AXIS_DROPDOWN_XPATH = "(//span[@class='ant-select-selection-item'])[2]";
	public static final String FLOW_METER_VS_FEEDING_PUMP_Y_AXIS_OPTION1_XPATH = "(//div[@class='ant-select-item-option-content'])[4]";
	public static final String FLOW_METER_VS_FEEDING_PUMP_Y_AXIS_OPTION2_XPATH = "(//div[@class='ant-select-item-option-content'])[5]";
	public static final String FLOW_METER_VS_FEEDING_PUMP_Y_AXIS_OPTION3_XPATH = "(//div[@class='ant-select-item-option-content'])[6]";
	public static final String FLOW_METER_AND_FEEDING_PUMP_X_AXIS_DROPDOWN_XPATH = "(//span[@class='ant-select-selection-item'])[5]";
	public static final String FLOW_METER_AND_FEEDING_PUMP_X_AXIS_OPTION1_XPATH = "(//div[@class='ant-select-item-option-content'])[7]";
	public static final String FLOW_METER_AND_FEEDING_PUMP_X_AXIS_OPTION2_XPATH = "(//div[@class='ant-select-item-option-content'])[8]";
	public static final String FLOW_METER_AND_FEEDING_PUMP_X_AXIS_OPTION3_XPATH = "(//div[@class='ant-select-item-option-content'])[9]";
	public static final String FLOW_METER_AND_FEEDING_PUMP_Y_AXIS_DROPDOWN_XPATH = "(//span[@class='ant-select-selection-item'])[6]";
	public static final String FLOW_METER_AND_FEEDING_PUMP_Y_AXIS_OPTION1_XPATH = "(//div[@class='ant-select-item-option-content'])[10]";
	public static final String FLOW_METER_AND_FEEDING_PUMP_Y_AXIS_OPTION2_XPATH = "(//div[@class='ant-select-item-option-content'])[11]";
	public static final String FLOW_METER_AND_FEEDING_PUMP_Y_AXIS_OPTION3_XPATH = "(//div[@class='ant-select-item-option-content'])[12]";
	public static final String PH_AND_TEMPERATURE_VS_TIME_X_AXIS_DROPDOWN_XPATH = "(//span[@class='ant-select-selection-item'])[7]";
	public static final String PH_AND_TEMPERATURE_VS_TIME_X_AXIS_OPTION1_XPATH = "(//div[@class='ant-select-item-option-content'])[13]";
	public static final String PH_AND_TEMPERATURE_VS_TIME_X_AXIS_OPTION2_XPATH = "(//div[@class='ant-select-item-option-content'])[14]";
	public static final String PH_AND_TEMPERATURE_VS_TIME_X_AXIS_OPTION3_XPATH = "(//div[@class='ant-select-item-option-content'])[15]";
	public static final String PH_AND_TEMPERATURE_VS_TIME_Y_AXIS_DROPDOWN_XPATH = "(//span[@class='ant-select-selection-item'])[8]";
	public static final String PH_AND_TEMPERATURE_VS_TIME_Y_AXIS_OPTION1_XPATH = "(//div[@class='ant-select-item-option-content'])[16]";
	public static final String PH_AND_TEMPERATURE_VS_TIME_Y_AXIS_OPTION2_XPATH = "(//div[@class='ant-select-item-option-content'])[17]";
	public static final String PH_AND_TEMPERATURE_VS_TIME_Y_AXIS_OPTION3_XPATH = "(//div[@class='ant-select-item-option-content'])[18]";
	public static final String CIRCULARITY_SUSTAINABILITY_XPATH = "//span[text()='Circularity and Sustainability']";
	public static final String INDICATORS_ISO_14000_XPATH = "//div[text()='Indicators in Compliance with ISO 14000']";
	public static final String INDICATORS_ISO_59000_XPATH = "//div[text()='Indicators in Compliance with ISO 59000']";
	public static final String ACTION_INDICATORS_XPATH = "//div[text()='ACTION Indicators']";
	public static final String CIRCULARITY_SUSTAINABILITY_DATERANGE_PICKER_XPATH = "//div[@class='ant-picker ant-picker-range ant-picker-filled css-j9bb5n']";
	public static final String CIRCULARITY_SUSTAINABILITY_STARTDATE_XPATH = "//input[@placeholder='Start date']";
	public static final String CIRCULARITY_SUSTAINABILITY_ENDDATE_XPATH = "//input[@placeholder='End date']";
	public static final String CIRCULARITY_SUSTAINABILITY_SEARCHBAR_XPATH = "//input[@class='ant-input css-j9bb5n']";
	public static final String SUSTAINABLE_PLANNING_XPATH = "//span[text()='Sustainable Strategic Planning']";
	public static final String SUSTAINABLE_PLANNING_NO_DATA_CLOSE_XPATH = "//button[@class='Toastify__close-button Toastify__close-button--dark']";
	public static final String SUSTAINABLE_PLANNING_DATERANGE_XPATH = "//div[@class='ant-picker ant-picker-range ant-picker-filled css-j9bb5n']";
	public static final String SUSTAINABLE_PLANNING_STARTDATE_XPATH = "//input[@placeholder='Start date']";
	public static final String SUSTAINABLE_PLANNING_ENDDATE_XPATH = "//input[@placeholder='End date']";
	public static final String SUSTAINABLE_PLANNING_SELECT_STARTDATE_XPATH = "//td[@title='2024-08-01']";
	public static final String SUSTAINABLE_PLANNING_SELECT_ENDDATE_XPATH = "//td[@title='2024-08-08']";
	public static final String SUSTAINABLE_PLANNING_DROPDOWN_XPATH = "//span[text()='Modify SRT']";
	public static final String SUSTAINABLE_PLANNING_SELECT_MODIFYSRT_XPATH = "//div[text()='Modify SRT']";
	public static final String SUSTAINABLE_PLANNING_SELECT_MODIFYINFLOW__XPATH = "//div[text()='Modify inflow volume']";
	public static final String SUSTAINABLE_PLANNING_RUNSIMULATION_XPATH = "//span[text()='Run Simulation']";
	public static final String SUSTAINABLE_PLANNING_SEARCHBAR_XPATH = "//input[@class='ant-input css-j9bb5n']";
	public static final String FORECASTING_XPATH = "//span[text()='Forecasting']";
	public static final String FORECASTING_DATE_PICKER_XPATH = "//input[@placeholder='Select date']";
	public static final String FORECASTING_SELECT_DATE_XPATH = "//td[@title='2024-08-01']";
	public static final String FORECASTING_HOUR_PICKER_XPATH = "(//div[@class='ant-picker-input'])[2]";
	public static final String FORECASTING_SELECT_HOUR_XPATH = "(//div[@class='ant-picker-time-panel-cell-inner'])[6]";
	public static final String FORECASTING_HOUR_OK_XPATH = "(//button[@type='button'])[9]";
	public static final String FORECASTING_MINUTE_PICKER_XPATH = "//input[@placeholder='Min']";
	public static final String FORECASTING_SELECT_MINUTE_XPATH = "(//div[text()='10'])[3]";
	public static final String FORECASTING_MINUTE_OK_XPATH = "(//button[@type='button'])[10]";
	public static final String FORECASTING_SELECT_REACTOR1_XPATH = "//input[@value='reactor01']";
	public static final String FORECASTING_SELECT_REACTOR2_XPATH = "//input[@value='reactor02']";
	public static final String FORECASTING_CHECKBOX_30_MIN_XPATH = "(//input[@class='ant-checkbox-input'])[1]";
	public static final String FORECASTING_CHECKBOX_60_MIN_XPATH = "(//input[@class='ant-checkbox-input'])[2]";
	public static final String FORECASTING_CHECKBOX_120_MIN_XPATH = "(//input[@class='ant-checkbox-input'])[3]";
	public static final String FORECASTING_START_FORECAST_XPATH = "//span[text()='Start Forecast']";
	public static final String FORECASTING_SEARCHBAR_XPATH = "//input[@class='ant-input css-j9bb5n']";
	public static final String SENSOR_EQUIPMENT_ALARMS_XPATH = "//span[text()='Sensor/Equipment Alarms']";
	public static final String SENSOR_EQUIPMENT_ALARMS_SEARCHBAR_XPATH = "//input[@class='ant-input css-j9bb5n']";
	public static final String SENSOR_EQUIPMENT_ALARMS_DATERANGE_PICKER_XPATH = "//div[@class='ant-picker ant-picker-range ant-picker-filled css-j9bb5n']";
	public static final String SENSOR_EQUIPMENT_ALARMS_STARTDATE_XPATH = "//td[@title='2024-08-05']";
	public static final String SENSOR_EQUIPMENT_ALARMS_ENDDATE_XPATH = "//td[@title='2024-08-14']";
	public static final String METEOROLOGICAL_CONDITIONS_XPATH = "//span[text()='Meteorological Conditions']";
	public static final String METEOROLOGICAL_CONDITIONS_AIR_TEMPERATURE_CHECKBOX_XPATH = "//input[@value='temperature']";
	public static final String METEOROLOGICAL_CONDITIONS_PRECIPITATION_CHECKBOX_XPATH = "//input[@value='precipitation']";
	public static final String METEOROLOGICAL_CONDITIONS_RADIATION_CHECKBOX_XPATH = "//input[@value='radiation']";
	public static final String METEOROLOGICAL_CONDITIONS_FORECAST_RESOLUTION_HOURLY_RADIO_XPATH = "//input[@value='hourly']";
	public static final String METEOROLOGICAL_CONDITIONS_FORECAST_RESOLUTION_DAILY_RADIO_XPATH = "//input[@value='daily']";
	public static final String METEOROLOGICAL_CONDITIONS_FORECAST_PERIOD_1DAY_RADIO_XPATH = "//input[@value='1']";
	public static final String METEOROLOGICAL_CONDITIONS_FORECAST_PERIOD_3DAY_RADIO_XPATH = "//input[@value='3']";
	public static final String METEOROLOGICAL_CONDITIONS_FORECAST_PERIOD_6DAY_RADIO_XPATH = "//input[@value='6']";
	public static final String METEOROLOGICAL_CONDITIONS_START_FORECAST_XPATH = "//span[text()='Start Forecast']";
	public static final String METEOROLOGICAL_CONDITIONS_SEARCHBAR_XPATH = "//input[@class='ant-input css-j9bb5n']";
}
